# Graph Neural Networks

In this tutorial, we will explore the implementation of graph neural networks and investigate what representations these networks learn. Along the way, we'll see how PyTorch Geometric and TensorBoardX can help us with constructing and training graph models.

# Preliminaries: PyTorch

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import sklearn.metrics as metrics

# Graph Neural Network
# We first need to load the Cora dataset:

In [2]:
from torch_geometric.datasets import Planetoid
import torch_geometric.transforms as T
dataset = Planetoid("Planetoid", name="Cora", transform=T.ToSparseTensor())

# Now let’s implement a two-layer GCN
The constructor defines two GCNConv layers which get called in the forward pass of our network. Note that the non-linearity is not integrated in the conv calls and hence needs to be applied afterwards (something which is consistent accross all operators in PyTorch Geometric). Here, we chose to use ReLU as our intermediate non-linearity between and finally output a softmax distribution over the number of classes. Let’s train this model on the train nodes for 200 epochs:

In [3]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
from torch_geometric.nn import SAGEConv
from the_sparse_package.tensor import SparseTensor

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = GCNConv(dataset.num_node_features, 16, cached=True)
        self.conv2 = GCNConv(16, dataset.num_classes, cached=True)

    def forward(self, data):
        x, adj_t = data.x, data.adj_t
        x = self.conv1(x, adj_t)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, adj_t)

        return F.log_softmax(x, dim=1)

# Let’s train this model on the train nodes for 200 epochs:

In [4]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)
data = dataset[0].to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

model.train()
for epoch in range(2):
    optimizer.zero_grad()
    out = model(data)
    loss = F.nll_loss(out[data.train_mask], data.y[data.train_mask])
    loss.backward()
    optimizer.step()
    
    _, pred = model(data).max(dim=1)
    correct = float (pred[data.train_mask].eq(data.y[data.train_mask]).sum().item())
    acc = correct / data.train_mask.sum().item()
    print('Epoch: %d, Accuracy: %.4f'%(epoch,acc))

gcn conv initialization
gcn conv initialization
gcn conv forward
gcn conv message and aggregate
aggr add
inside the_sparse_package matmul function
going into spmm
output from the cpp function  inside the cpp function 
tensor([1])
output from the cpp function 2  inside the cpp function in a new file 
tensor([2])
inside spmm sum
inside the spmm_sum cpp function 
gcn conv forward
gcn conv message and aggregate
aggr add
inside the_sparse_package matmul function
going into spmm
output from the cpp function  inside the cpp function 
tensor([1])
output from the cpp function 2  tensor([2])
inside spmm sum
inside the cpp function in a new file 
inside the spmm_sum cpp function 
gcn conv forward
gcn conv message and aggregate
aggr add
inside the_sparse_package matmul function
going into spmm
output from the cpp function  inside the cpp function 
tensor([1])
output from the cpp function 2  inside the cpp function in a new file 
tensor([2])
inside spmm sum
inside the spmm_sum cpp function 
gcn con

# Finally we can evaluate our model on the test nodes:

In [5]:
_, pred = model(data).max(dim=1)
correct = float (pred[data.test_mask].eq(data.y[data.test_mask]).sum().item())
acc = correct / data.test_mask.sum().item()
print('Accuracy: {:.4f}'.format(acc))

gcn conv forward
gcn conv message and aggregate
aggr add
inside the_sparse_package matmul function
going into spmm
output from the cpp function  inside the cpp function 
tensor([1])
output from the cpp function 2  tensor([2])
inside spmm sum
inside the cpp function in a new file 
inside the spmm_sum cpp function 
gcn conv forward
gcn conv message and aggregate
aggr add
inside the_sparse_package matmul function
going into spmm
output from the cpp function  inside the cpp function 
tensor([1])
output from the cpp function 2  inside the cpp function in a new file 
tensor([2])
inside spmm sum
inside the spmm_sum cpp function 
Accuracy: 0.5060


More examples: https://github.com/rusty1s/pytorch_geometric/tree/master/examples